### PR TITLE
WIP: Add rs_init_printf and family

### PR DESCRIPTION
**Pull request by iamthad**
Add a series of functions for initializing a rapidstring from a printf format string and arguments.

A common trick for `sprintf` into an allocated string is to first get the length by calling
```c
snprintf(NULL, 0, ...)
```
and then allocate that length and call `snprintf` again.

However, with rapidstring, the first call can use the stack buffer and length instead and possibly avoid a second `snprintf` call if the stack was big enough.

An alternate implementation could use [`asprintf`](http://man7.org/linux/man-pages/man3/asprintf.3.html) and `rs_steal`, but there are two disadvantages:
1. `asprintf` is a GNU extension
2. Even very tiny strings would end up on the heap.

----

These functions still need documentation and test coverage.

### CODE REVIEW

**Comment by boyerjohn** [comment]
Thank you for the contribution, but unfortunately I cannot accept it. These functions are too narrow to be included in a general purpose string library. The problem you presented could be solved without using any rapidstring internals, and therefore doesn't really need a library solution. I want to keep this library minimalistic.
```cpp
rapidstring s;
rs_init(&s);
int needed = snprintf(rs_data(&s), rs_cap(&s), ...);

if (needed <= rs_cap(&s)) {
        rs_reserve(&s, needed);
        snprintf(rs_data(&s), needed, ...);
}
```

**Comment by iamthad** [comment]
I agree, that solution, which I hadn't considered, is better than adding this to the library.

**Comment by boyerjohn** [comment]
@iamthad Here's a few touch-ups to my solution for better performance, if you do end up using it.
```cpp
rapidstring s;
rs_init(&s);
int needed = snprintf(rs_data(&s), RS_STACK_CAPACITY + 1, ...);

if (needed <= RS_STACK_CAPACITY) {
        rs_heap_init(&s, needed);
        snprintf(rs_data(&s), needed, ...);
}
```
Three changes:
1. Uses the stack capacity constant rather than calling the capacity function.
2. Adds the `+ 1` in the `snprintf` call, since it is supposed to include the null terminator in the capacity.
3. `rs_heap_init` rather than `rs_reserve` since the previous data is never read, and therefore doesn't need to be copied from the heap string to the stack string.

Also, if you really want to squeeze out the performance, you could substitute both `rs_data()` calls with `s->stack.buffer` and `s->heap.buffer` respectively, since you know the state of the string in these circumstances.

**Comment by boyerjohn** [comment]
> Should that condition be needed >= rs_cap(&s) rather than <=?

Yes, fixed.

**Comment by iamthad** [comment]
How should the length of the string be set in your example?

**Comment by boyerjohn** [comment]
`rs_resize(&s, needed)` or `rs_heap_resize` since you know it's on the heap.

Or you could assign `s.heap.size` to save an instruction or two that sets the null terminator.

**Pull request closed without merging**
