### PR TITLE
Allow custom storage

### PR DESCRIPTION
**Pull request by Qix-**
This allows consumers to pre-define `RS_API` in order to specify custom linkage/storage. This is required for certain language bindings since `static` storage doesn't work in all cases, but the base-case defaults to `static` storage.

### CODE REVIEW

**Comment by boyerjohn** [comment]
Thanks for the PR, if only `clang-format` let you configure the indentation width for macros. This is going to get hard to manage with so many nested `#if`s.

**Comment by Qix-** [comment]
I do this, personally:

```c
#ifdef SOMETHING
#	ifdef SOMETHING_ELSE
#		define RESULT
#	else
#		define OTHER_RESULT
#	endif
#endif
```

**Comment by boyerjohn** [comment]
`clang-format` also uses whatever your normal indentation is, but I think 8 spaces for marcos is too much, especially because of the 80 character limit. Macros are already ugly, and forcing them on multiple lines with backslashes would be a mess.

**Comment by Qix-** [comment]
Those are hard tabs, so it'd be whatever the user's editor is configured to use.

That's not to say you can't use spaces - Github doesn't set the css property `tab-size` and thus most browsers default to a width of 8, which is why my example has 8 😅. I was more illustrating the format of `#<indentation>thing` instead of `<indentation>#thing` or flat (`#thing`, no indentation).

**Pull request merged**
